import type { MCPServerConfig, MCPTool, ToolHandler, EnvVar } from '../mapper/types';

/**
 * Generate a complete Python MCP server from the server config.
 * Returns a map of filename → content.
 */
export function generatePythonServer(config: MCPServerConfig): Record<string, string> {
  const files: Record<string, string> = {};

  files['pyproject.toml'] = generatePyproject(config);
  files['server.py'] = generateServerPy(config);
  files['.env.example'] = generateEnvExample(config);
  files['Dockerfile'] = generateDockerfile(config);
  files['README.md'] = generateReadme(config);

  return files;
}

// ─── pyproject.toml ──────────────────────────────────────────────

function generatePyproject(config: MCPServerConfig): string {
  return `[project]
name = "mcp-${config.name}"
version = "${config.version}"
description = "${escapePy(config.description)}"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.0.0",
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
`;
}

// ─── Server ──────────────────────────────────────────────────────

function generateServerPy(config: MCPServerConfig): string {
  const toolFunctions = config.tools
    .filter(t => t.enabled)
    .map(t => generatePyTool(t))
    .join('\n\n');

  return `"""${config.name} MCP Server

${config.description}

Generated by MCPForge (https://mcpforge.dev)
"""

import os
import json
import httpx
from mcp.server.fastmcp import FastMCP
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv("API_BASE_URL", "${escapePy(config.baseUrl)}")

mcp = FastMCP("${escapePy(config.name)}")

${toolFunctions}

if __name__ == "__main__":
    mcp.run()
`;
}

function generatePyTool(tool: MCPTool): string {
  const h = tool.handler;
  const params = generatePyParams(tool);
  const body = generatePyHandlerBody(tool);

  return `@mcp.tool()
async def ${tool.name}(${params}) -> str:
    """${escapePy(tool.description)}"""
${body}`;
}

function generatePyParams(tool: MCPTool): string {
  const params: string[] = [];

  for (const [name, prop] of Object.entries(tool.inputSchema.properties)) {
    const p = prop as { type: string; description?: string; enum?: unknown[] };
    const pyType = mapToPyType(p);
    const isRequired = tool.inputSchema.required.includes(name);

    if (isRequired) {
      params.push(`${name}: ${pyType}`);
    } else {
      params.push(`${name}: ${pyType} | None = None`);
    }
  }

  return params.join(', ');
}

function mapToPyType(prop: { type: string }): string {
  switch (prop.type) {
    case 'string': return 'str';
    case 'number': return 'float';
    case 'boolean': return 'bool';
    case 'array': return 'list';
    case 'object': return 'dict';
    default: return 'str';
  }
}

function generatePyHandlerBody(tool: MCPTool): string {
  const h = tool.handler;
  const lines: string[] = [];

  // Build URL
  let urlExpr = `f"{BASE_URL}${h.path}"`;
  if (h.pathParams.length > 0) {
    urlExpr = `f"{BASE_URL}${h.path.replace(/\{([^}]+)\}/g, (_, name) => `{${name}}`)}"`;
  }
  lines.push(`    url = ${urlExpr}`);

  // Query params
  if (h.queryParams.length > 0) {
    lines.push(`    params = {}`);
    for (const qp of h.queryParams) {
      lines.push(`    if ${qp} is not None:`);
      lines.push(`        params["${qp}"] = ${qp}`);
    }
  }

  // Headers with auth
  lines.push(`    headers = {"Accept": "application/json"}`);
  for (const auth of h.auth) {
    if (auth.scheme.type === 'http' && auth.scheme.scheme === 'bearer') {
      lines.push(`    headers["Authorization"] = f"Bearer {os.getenv('${auth.envVar}', '')}"`);
    } else if (auth.scheme.type === 'apiKey' && auth.scheme.in === 'header') {
      lines.push(`    headers["${auth.scheme.paramName || 'X-API-Key'}"] = os.getenv("${auth.envVar}", "")`);
    }
  }

  // Body
  let hasBody = false;
  if (h.bodyParam === '__body_object__') {
    const exclude = [...h.pathParams, ...h.queryParams, ...h.headerParams];
    const bodyKeys = Object.keys(tool.inputSchema.properties).filter(k => !exclude.includes(k));
    if (bodyKeys.length > 0) {
      lines.push(`    body = {`);
      for (const key of bodyKeys) {
        lines.push(`        "${key}": ${key},`);
      }
      lines.push(`    }`);
      lines.push(`    body = {k: v for k, v in body.items() if v is not None}`);
      hasBody = true;
    }
  } else if (h.bodyParam) {
    lines.push(`    body = ${h.bodyParam}`);
    hasBody = true;
  }

  // Make request
  lines.push('');
  lines.push('    async with httpx.AsyncClient() as client:');
  const requestParts = [`url`];
  if (h.queryParams.length > 0) requestParts.push('params=params');
  requestParts.push('headers=headers');
  if (hasBody) requestParts.push('json=body');
  requestParts.push('timeout=30.0');

  lines.push(`        response = await client.${h.method.toLowerCase()}(${requestParts.join(', ')})`);
  lines.push('        response.raise_for_status()');
  lines.push('');
  lines.push('        try:');
  lines.push('            return json.dumps(response.json(), indent=2)');
  lines.push('        except Exception:');
  lines.push('            return response.text');

  return lines.join('\n');
}

// ─── Env Example ─────────────────────────────────────────────────

function generateEnvExample(config: MCPServerConfig): string {
  const lines = [
    `# ${config.name} MCP Server - Environment Variables`,
    `# Copy this to .env and fill in your values`,
    '',
  ];

  for (const envVar of config.envVars) {
    lines.push(`# ${envVar.description}`);
    lines.push(`${envVar.name}=${envVar.example || ''}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Dockerfile ──────────────────────────────────────────────────

function generateDockerfile(config: MCPServerConfig): string {
  return `FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml ./
RUN pip install .
COPY . .
CMD ["python", "server.py"]
`;
}

// ─── README ──────────────────────────────────────────────────────

function generateReadme(config: MCPServerConfig): string {
  const toolList = config.tools
    .filter(t => t.enabled)
    .map(t => `- **${t.name}** — ${t.description}`)
    .join('\n');

  return `# ${config.name} MCP Server

${config.description}

> Generated by [MCPForge](https://mcpforge.dev)

## Quick Start

\`\`\`bash
pip install -e .
cp .env.example .env
# Edit .env with your API credentials
python server.py
\`\`\`

## Tools

${toolList}

## Usage with Claude Desktop

Add to your \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${config.name}": {
      "command": "python",
      "args": ["server.py"]
    }
  }
}
\`\`\`
`;
}

function escapePy(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}
