import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'MCPForge terms of service — rules and guidelines for using our platform.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-gray-400 mb-10 text-sm">Last updated: June 28, 2025</p>

      <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 text-[15px] leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-white mb-3">1. Agreement to Terms</h2>
          <p>
            By accessing or using MCPForge (the &quot;Service&quot;), operated by Claudius Inc.
            (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these
            Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
          <p>
            MCPForge is a developer tool that generates Model Context Protocol (MCP) servers from
            OpenAPI specifications, natural language descriptions, or API documentation. The Service
            includes a web application, code generation engine, server registry, and related APIs.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">3. Accounts</h2>
          <p>
            To access certain features, you must sign in using GitHub OAuth. You are responsible
            for maintaining the security of your GitHub account. You agree to notify us immediately
            of any unauthorized use of your account.
          </p>
          <p className="mt-2">
            We reserve the right to suspend or terminate accounts that violate these Terms or
            engage in abusive behavior.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service for any unlawful purpose</li>
            <li>Generate MCP servers that facilitate illegal activities</li>
            <li>Attempt to reverse engineer, decompile, or disassemble the Service</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Abuse rate limits or circumvent usage restrictions</li>
            <li>Scrape, crawl, or data-mine the Service beyond normal API usage</li>
            <li>Impersonate another person or entity</li>
            <li>Upload malicious OpenAPI specs or inputs designed to exploit the system</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">5. Generated Code &amp; Intellectual Property</h2>

          <h3 className="text-lg font-medium text-gray-200 mt-4 mb-2">Your Content</h3>
          <p>
            You retain ownership of the OpenAPI specs, descriptions, and other inputs you provide
            to the Service. By submitting content, you grant us a limited license to process it
            for the purpose of providing the Service.
          </p>

          <h3 className="text-lg font-medium text-gray-200 mt-4 mb-2">Generated Output</h3>
          <p>
            Code generated by MCPForge is provided to you under the MIT License unless otherwise
            specified. You are free to use, modify, and distribute generated code in your own
            projects. We do not claim ownership of generated output.
          </p>

          <h3 className="text-lg font-medium text-gray-200 mt-4 mb-2">Our Intellectual Property</h3>
          <p>
            The Service, including its design, code generation engine, branding, and documentation,
            is owned by Claudius Inc. and protected by intellectual property laws. These Terms do
            not grant you rights to our trademarks, logos, or branding.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">6. Subscriptions &amp; Billing</h2>
          <p>
            Certain features require a paid subscription. Payments are processed by Stripe. By
            subscribing, you agree to pay the applicable fees.
          </p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Subscriptions renew automatically unless canceled before the renewal date</li>
            <li>You may cancel your subscription at any time from your dashboard</li>
            <li>Refunds are handled on a case-by-case basis at our discretion</li>
            <li>We reserve the right to change pricing with 30 days&apos; notice</li>
            <li>Free tier usage is subject to rate limits and may change at any time</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">7. Registry &amp; Published Servers</h2>
          <p>
            If you publish MCP servers to the MCPForge Registry, you represent that you have the
            right to share that content. We may remove published servers that violate these Terms
            or that we deem harmful. Published servers may be used by other users in accordance
            with their specified license.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">8. Disclaimers</h2>
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
            WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT:
          </p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Generated code will be error-free, secure, or fit for any particular purpose</li>
            <li>The Service will be uninterrupted or available at all times</li>
            <li>Generated MCP servers will be compatible with all MCP clients</li>
            <li>AI-generated code will meet your specific requirements</li>
          </ul>
          <p className="mt-2">
            You are solely responsible for testing, reviewing, and validating any generated code
            before deploying it to production environments.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, CLAUDIUS INC. SHALL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF
            PROFITS, DATA, OR BUSINESS OPPORTUNITIES, ARISING FROM YOUR USE OF THE SERVICE.
          </p>
          <p className="mt-2">
            Our total aggregate liability for any claims arising from or relating to the Service
            shall not exceed the amount you paid us in the twelve (12) months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">10. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Claudius Inc. and its officers, directors,
            employees, and agents from any claims, damages, losses, or expenses (including
            reasonable attorneys&apos; fees) arising from your use of the Service or violation of
            these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">11. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service at any time, with or without
            cause, with or without notice. Upon termination, your right to use the Service ceases
            immediately. Provisions that by their nature should survive termination will survive.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">12. Changes to Terms</h2>
          <p>
            We may modify these Terms at any time. We will notify you of material changes by
            updating the &quot;Last updated&quot; date. Your continued use of the Service after
            changes constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">13. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws of the State of
            Delaware, United States, without regard to conflict of law principles. Any disputes
            shall be resolved in the courts located in Delaware.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">14. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions
            will remain in full force and effect.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">15. Contact</h2>
          <p>
            For questions about these Terms, contact Claudius Inc. at:{' '}
            <a href="mailto:legal@mcpforge.dev" className="text-forge-400 hover:underline">
              legal@mcpforge.dev
            </a>
          </p>
        </section>
      </div>

      <footer className="mt-16 pt-8 border-t border-gray-800 text-center text-sm text-gray-500">
        <a href="/privacy" className="text-gray-400 hover:text-white mr-6">Privacy Policy</a>
        <a href="/" className="text-gray-400 hover:text-white">Back to MCPForge</a>
      </footer>
    </div>
  );
}
